# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-preview.7.23376.3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity quiet --logger:"xunit;LogFilePath=$(pwd)/TestResults/smink.UnitTests.testresults.xml" smink.UnitTests
    
    - name: Create test report (dogfooding)
      if: always()
      run: |
        dotnet run --project smink -- ./TestResults/smink.UnitTests.testresults.xml ./TestResults/smink.UnitTests.testresults.html
#        echo '<![CDATA[' > $GITHUB_STEP_SUMMARY
#        cat ./TestResults/smink.UnitTests.testresults.html >> $GITHUB_STEP_SUMMARY
#        echo ']]>' >> $GITHUB_STEP_SUMMARY
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with: 
        name: test-report
        path: TestResults
